### ISSUE TITLE
rss feed

### ISSUE THREAD

**Issue by iloveitaly** [andreasklinger/klinger-io#5]
Would be great if there was an rss feed I could subscribe to :) Great posts.

**Comment by fabian-hiller** [comment]
Hey @iloveitaly thanks for your feedback. As soon as I have the time, I will have a look.

**Comment by fabian-hiller** [comment]
Hey @iloveitaly, I just added the [RSS feed](https://klinger.io/rss.xml). Thank you again for your feedback. Feel free to let me know if something is not working or can be improved.
